
[source]
url = "https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"

[snowflake]
account = "TUHKAOM-UX01625"
warehouse = "COMPUTE_WH"
database = "tpcds"
schema = "RAW"
role = "accountadmin"
stage_name = "inventory_Stage"
file_format = "comma_csv"
table = "inventory"

[local]
destination_folder = "/tmp"
file_name = "inventory.csv"
local_file_path = "/tmp/inventory.csv"